"use client";
import {useEffect,useRef,useState,type ChangeEvent} from "react";
import {db} from "@/src/db/database";
import type {GoodsReceipt,InventoryItem,Permission,ProcurementOrder,Supplier,UserRole,Warehouse} from "@/src/domain/models";
import {createPurchaseOrder,createPurchaseRequest,paySupplierInvoices,postGoodsReceipt,postPurchaseReturn,postSupplierInvoice,submitPurchaseOrder,submitPurchaseRequest} from "@/src/domain/purchasing-service";
import {decideApproval} from "@/src/domain/approval-service";
import {permissionsForRole,roleHasPermission} from "@/src/domain/authorization-service";
import {createLocalUser} from "@/src/domain/user-service";
import {createBackup,downloadBackup,restoreBackup,validateBackup} from "@/src/domain/backup-service";
import {expenseReport,exportCsv,productProfitability,productionReport,purchaseReport,salesReport,shiftReport,stockMovementReport,supplierAging,wasteReport} from "@/src/domain/reporting-service";
import {formatMoney} from "@/src/lib/money";

type Tab="purchasing"|"approvals"|"users"|"backup"|"reports";
const tabPermission:Record<Tab,Permission>={purchasing:"purchases.request",approvals:"approvals.decide",users:"users.manage",backup:"backup.manage",reports:"reports.operational"};

export function BusinessControlModule({username,role,notify}:{username:string;role:UserRole;notify:(t:string,e?:boolean)=>void}){
  const tabs=(["purchasing","approvals","users","backup","reports"] as Tab[]).filter(x=>roleHasPermission(role,tabPermission[x])||(x==="purchasing"&&permissionsForRole(role).some(p=>p.startsWith("purchases.")))||(x==="reports"&&roleHasPermission(role,"reports.financial")));
  const[tab,setTab]=useState<Tab>(tabs[0]??"purchasing"),[tick,setTick]=useState(0);const refresh=()=>setTick(x=>x+1),run=async(fn:()=>Promise<unknown>,m:string)=>{try{await fn();refresh();notify(m)}catch(e){notify(e instanceof Error?e.message:"تعذر التنفيذ",true)}};
  if(!tabs.length)return <Panel title="لا توجد صلاحيات"><p>هذا المستخدم لا يملك صلاحية دخول أقسام الإدارة.</p></Panel>;
  const labels:Record<Tab,string>={purchasing:"المشتريات",approvals:"الموافقات",users:"المستخدمون والصلاحيات",backup:"النسخ والاستعادة",reports:"التقارير التشغيلية"};
  return <div><div className="finance-tabs">{tabs.map(id=><button className={tab===id?"active":""} key={id} onClick={()=>setTab(id)}>{labels[id]}</button>)}</div>{tab==="purchasing"&&<Purchasing key={tick} user={username} role={role} run={run}/>} {tab==="approvals"&&<Approvals key={tick} user={username} role={role} run={run}/>} {tab==="users"&&<Users key={tick} actor={username} role={role} run={run}/>} {tab==="backup"&&<BackupCenter run={run}/>} {tab==="reports"&&<Reports/>}</div>;
}

function useRows<T>(load:()=>Promise<T[]>){const[rows,setRows]=useState<T[]>([]),loader=useRef(load);useEffect(()=>{loader.current().then(setRows)},[]);return rows}

function Purchasing({user,role,run}:{user:string;role:UserRole;run:(f:()=>Promise<unknown>,m:string)=>void}){
  const requests=useRows(()=>db.purchaseRequests.orderBy("requestDate").reverse().toArray()),orders=useRows(()=>db.procurementOrders.orderBy("orderDate").reverse().toArray()),receipts=useRows(()=>db.goodsReceipts.orderBy("receiptDate").reverse().toArray()),invoices=useRows(()=>db.supplierInvoiceRecords.orderBy("invoiceDate").reverse().toArray()),items=useRows(()=>db.items.where("stage").equals("raw").toArray()),warehouses=useRows(()=>db.warehouses.where("stage").equals("raw").toArray()),suppliers=useRows(()=>db.suppliers.toArray()),requestLines=useRows(()=>db.purchaseRequestLines.toArray()),orderLines=useRows(()=>db.procurementOrderLines.toArray()),accounts=useRows(()=>db.accounts.where("active").equals(1).toArray());
  return <>
    {roleHasPermission(role,"purchases.request")&&<Panel title="طلب شراء جديد"><RequestForm user={user} role={role} items={items} warehouses={warehouses} run={run}/></Panel>}
    <Panel title="طلبات الشراء">{requests.length?requests.map(r=><Row key={r.id} title={r.number} text={`${r.requiredDate} · ${status(r.status)}`} actions={r.status==="draft"&&roleHasPermission(role,"purchases.request")?<button className="btn small primary" onClick={()=>run(()=>submitPurchaseRequest(r.id,role,user),"تم إرسال الطلب للموافقة")}>إرسال للموافقة</button>:r.status==="approved"&&roleHasPermission(role,"purchases.create_order")?<button className="btn small green" disabled={!suppliers.length} onClick={()=>{const lines=requestLines.filter(x=>x.purchaseRequestId===r.id);run(()=>createPurchaseOrder({role,user,requestId:r.id,supplierId:suppliers[0].id,warehouseId:r.warehouseId,expectedDeliveryDate:r.requiredDate,lines:lines.map(x=>({itemId:x.itemId,orderedQuantity:x.requestedQuantity,unitId:x.unitId,unitPricePiasters:x.estimatedCostPiasters,discountPiasters:0,vatRate:14}))}),"تم تحويل الطلب إلى أمر شراء مسودة")}}>تحويل لأمر</button>:null}/>):<Empty text="لا توجد طلبات شراء"/>}</Panel>
    <Panel title="أوامر الشراء والاستلام">{orders.length?orders.map(o=>{const lines=orderLines.filter(x=>x.purchaseOrderId===o.id);return <Row key={o.id} title={o.number} text={`${suppliers.find(s=>s.id===o.supplierId)?.name??""} · ${status(o.status)} · ${formatMoney(o.totalPiasters)}`} actions={<>{o.status==="draft"&&roleHasPermission(role,"purchases.create_order")&&<button className="btn small primary" onClick={()=>run(()=>submitPurchaseOrder(o.id,role,user),"تم إرسال أمر الشراء للموافقة")}>إرسال للموافقة</button>}{["approved","partially_received"].includes(o.status)&&roleHasPermission(role,"purchases.receive")&&<ReceiveButton order={o} lines={lines} role={role} user={user} run={run}/>}</>}/>}) : <Empty text="لا توجد أوامر شراء"/>}</Panel>
    <Panel title="إيصالات الاستلام وفواتير المورد">{receipts.length?receipts.map(g=><ReceiptRow key={g.id} receipt={g} orders={orders} suppliers={suppliers} user={user} role={role} run={run}/>):<Empty text="لا توجد إيصالات استلام"/>}</Panel>
    <Panel title="فواتير الموردين والسداد">{invoices.length?invoices.map(invoice=><Row key={invoice.id} title={invoice.number} text={`${suppliers.find(x=>x.id===invoice.supplierId)?.name??""} · ${status(invoice.matchingStatus)} · ${formatMoney(invoice.paidPiasters)} مدفوع من ${formatMoney(invoice.totalPiasters)} · ${status(invoice.status)}`} actions={invoice.status!=="paid"&&roleHasPermission(role,"purchases.pay")?<button className="btn small green" disabled={!accounts.length} onClick={()=>{const outstanding=invoice.totalPiasters-invoice.paidPiasters,entered=window.prompt(`المتبقي ${formatMoney(outstanding)} — اكتب مبلغ السداد بالجنيه`,String(outstanding/100));if(!entered)return;run(()=>paySupplierInvoices({role,user,supplierId:invoice.supplierId,date:new Date().toISOString().slice(0,10),paymentMethod:"cash",paymentAccountId:accounts.find(x=>x.code==="1110")?.id??accounts[0].id,allocations:[{supplierInvoiceId:invoice.id,amountPiasters:Math.round(Number(entered)*100)}]}),"تم تسجيل السداد وتحديث رصيد الفاتورة")}}>تسجيل سداد</button>:null}/>):<Empty text="لا توجد فواتير موردين"/>}</Panel>
  </>;
}

function ReceiveButton({order,lines,role,user,run}:{order:ProcurementOrder;lines:Array<{id:string;orderedQuantity:number;receivedQuantity:number}>;role:UserRole;user:string;run:(f:()=>Promise<unknown>,m:string)=>void}){const line=lines.find(x=>x.receivedQuantity<x.orderedQuantity);if(!line)return null;const remaining=line.orderedQuantity-line.receivedQuantity;return <button className="btn small green" onClick={()=>{const entered=window.prompt(`الكمية المتبقية ${remaining}. أدخل المستلم الآن:`,String(remaining));if(!entered)return;run(()=>postGoodsReceipt({role,user,purchaseOrderId:order.id,lines:[{purchaseOrderLineId:line.id,quantity:Number(entered)}]}),"تم الاستلام وتحديث المخزون مرة واحدة")}}>استلام جزئي / كامل</button>}

function RequestForm({user,role,items,warehouses,run}:{user:string;role:UserRole;items:InventoryItem[];warehouses:Warehouse[];run:(f:()=>Promise<unknown>,m:string)=>void}){const[item,setItem]=useState(""),[qty,setQty]=useState(""),[cost,setCost]=useState("");const selected=items.find(x=>x.id===item),warehouse=warehouses[0];return <form className="inline-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget),warehouseId=String(form.get("warehouse"));run(async()=>{const balance=await db.balances.get(`${warehouseId}:${item}`);return createPurchaseRequest({role,user,requiredDate:String(form.get("date")),warehouseId,lines:[{itemId:item,currentStock:balance?.quantity??0,minimumStock:selected?.minLevel??0,requestedQuantity:Number(qty),unitId:selected?.purchaseUnitId??"",estimatedCostPiasters:Math.round(Number(cost)*100)}]})},"تم إنشاء طلب الشراء دون تغيير الرصيد")}}><select name="warehouse" required defaultValue={warehouse?.id??""}><option value="">المخزن</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.nameAr}</option>)}</select><select value={item} onChange={e=>{setItem(e.target.value);const next=items.find(x=>x.id===e.target.value);if(next&&warehouse)db.balances.get(`${warehouse.id}:${next.id}`).then(b=>setQty(String(Math.max(0,next.minLevel-(b?.quantity??0)))));}} required><option value="">الصنف</option>{items.map(x=><option key={x.id} value={x.id}>{x.nameAr}</option>)}</select><input type="number" step=".001" value={qty} onChange={e=>setQty(e.target.value)} placeholder="الكمية المطلوبة" required/><input type="number" step=".01" value={cost} onChange={e=>setCost(e.target.value)} placeholder="تكلفة الوحدة التقديرية" required/><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><button className="btn primary">إنشاء الطلب</button></form>}

function ReceiptRow({receipt,orders,suppliers,user,role,run}:{receipt:GoodsReceipt;orders:ProcurementOrder[];suppliers:Supplier[];user:string;role:UserRole;run:(f:()=>Promise<unknown>,m:string)=>void}){const[invoiced,setInvoiced]=useState(false);useEffect(()=>{db.supplierInvoiceRecords.where("goodsReceiptId").equals(receipt.id).first().then(x=>setInvoiced(Boolean(x)))},[receipt.id]);return <Row title={receipt.number} text={`${orders.find(x=>x.id===receipt.purchaseOrderId)?.number} · ${suppliers.find(x=>x.id===receipt.supplierId)?.name}`} actions={<>{!invoiced&&roleHasPermission(role,"purchases.invoice")?<button className="btn small primary" onClick={()=>run(async()=>{const lines=await db.goodsReceiptLines.where("goodsReceiptId").equals(receipt.id).toArray();await postSupplierInvoice({role,user,supplierInvoiceNumber:`SUP-${receipt.number}`,supplierId:receipt.supplierId,invoiceDate:receipt.receiptDate,dueDate:receipt.receiptDate,purchaseOrderId:receipt.purchaseOrderId,goodsReceiptId:receipt.id,lines:lines.map(x=>({itemId:x.itemId,quantity:x.quantity,unitId:x.unitId,unitCostPiasters:x.unitCostPiasters,discountPiasters:0,vatRate:14}))})},"تم إثبات الفاتورة دون تكرار كمية المخزون")}>إثبات فاتورة</button>:invoiced?<span className="badge green">تمت الفوترة</span>:null}{roleHasPermission(role,"purchases.return")&&<button className="btn small danger" onClick={()=>run(async()=>{const line=(await db.goodsReceiptLines.where("goodsReceiptId").equals(receipt.id).toArray())[0];if(!line)throw new Error("لا يوجد بند للاسترجاع");const entered=window.prompt(`أدخل كمية المرتجع بحد أقصى ${line.quantity}`);if(!entered)throw new Error("تم إلغاء المرتجع");await postPurchaseReturn({role,user,supplierId:receipt.supplierId,goodsReceiptId:receipt.id,warehouseId:receipt.warehouseId,itemId:line.itemId,quantity:Number(entered),unitId:line.unitId,unitCostPiasters:line.unitCostPiasters,vatRate:14,reason:"other"})},"تم خصم المرتجع وتحديث حساب المورد")}>مرتجع</button>}</>}/>}

function Approvals({user,role,run}:{user:string;role:UserRole;run:(f:()=>Promise<unknown>,m:string)=>void}){const rows=useRows(()=>db.approvals.orderBy("requestedAt").reverse().toArray());return <Panel title="صندوق الموافقات الموحد">{rows.length?rows.map(x=><Row key={x.id} title={x.reference} text={`${x.entityType} · منشئه ${x.requestedBy} · ${status(x.status)}`} actions={x.status==="pending"?<><button className="btn small green" onClick={()=>run(()=>decideApproval(x.id,"approved",role,user),"تمت الموافقة")}>موافقة</button><button className="btn small danger" onClick={()=>run(()=>decideApproval(x.id,"rejected",role,user,"مرفوض من شاشة الموافقات"),"تم الرفض")}>رفض</button></>:null}/>):<Empty text="لا توجد موافقات"/>}</Panel>}

function Users({actor,role,run}:{actor:string;role:UserRole;run:(f:()=>Promise<unknown>,m:string)=>void}){const rows=useRows(()=>db.users.toArray());const roles:UserRole[]=["OWNER","MANAGER","ACCOUNTANT","STOREKEEPER","CASHIER","KITCHEN"];return <><Panel title="مستخدم محلي جديد"><form className="inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>createLocalUser({actorRole:role,actor,username:String(f.get("username")),displayName:String(f.get("name")),password:String(f.get("password")),role:String(f.get("role")) as UserRole}),"تم إنشاء المستخدم ويمكنه تسجيل الدخول الآن")}}><input name="name" placeholder="الاسم" required/><input name="username" placeholder="اسم المستخدم" required/><input name="password" type="password" minLength={6} placeholder="كلمة المرور" required/><select name="role">{roles.map(x=><option key={x}>{x}</option>)}</select><button className="btn primary">إضافة مستخدم</button></form></Panel><Panel title="المستخدمون والأدوار">{rows.map(x=><Row key={x.id} title={x.displayName} text={`${x.username} · ${x.role} · ${x.active?"نشط":"متوقف"} · ${permissionsForRole(x.role).length} صلاحية`}/>)}</Panel></>}

function BackupCenter({run}:{run:(f:()=>Promise<unknown>,m:string)=>void}){const[file,setFile]=useState<File>(),[summary,setSummary]=useState("");const inspect=async(e:ChangeEvent<HTMLInputElement>)=>{const selected=e.target.files?.[0];if(!selected)return;try{const parsed=JSON.parse(await selected.text()),valid=validateBackup(parsed);setFile(selected);setSummary(`${valid.restaurantName} · ${valid.createdAt} · ${valid.manifest.reduce((s,x)=>s+x.count,0)} سجل — صالح للاستعادة`)}catch(error){setFile(undefined);setSummary(error instanceof Error?error.message:"ملف غير صالح")}};return <Panel title="مركز النسخ الاحتياطي والاستعادة"><div className="backup-actions"><button className="btn primary" onClick={()=>run(async()=>downloadBackup(await createBackup()),"تم إنشاء النسخة وتنزيلها")}>إنشاء وتنزيل نسخة كاملة</button><label className="compact-upload"><input type="file" accept=".json,application/json" onChange={inspect}/>اختيار نسخة والتحقق منها</label>{summary&&<div className="operation-alert amber">{summary}</div>}<button className="btn danger" disabled={!file} onClick={()=>{if(file&&window.confirm("سيتم إنشاء نسخة أمان ثم استبدال البيانات داخل معاملة واحدة. هل أنت متأكد؟"))run(async()=>restoreBackup(JSON.parse(await file.text())),"تمت الاستعادة والتحقق من البيانات")}}>استعادة النسخة المحددة</button></div></Panel>}

function Reports(){const[from,setFrom]=useState(new Date().toISOString().slice(0,8)+"01"),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[rows,setRows]=useState<Array<Record<string,string|number|undefined>>>([]);return <><Panel title="تقرير المبيعات والربحية"><div className="inline-form"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="btn primary" onClick={async()=>setRows(await salesReport({from,to}))}>عرض التقرير</button><button className="btn" onClick={()=>exportCsv("restaurantflow-sales",rows)}>CSV</button></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>المرجع</th><th>المنتج</th><th>الكمية</th><th>صافي البيع</th><th>VAT</th><th>الربح</th></tr></thead><tbody>{rows.map((x,i)=><tr key={i}><td>{x.date}</td><td>{x.reference}</td><td>{x.product}</td><td>{x.quantity}</td><td>{formatMoney(Number(x.netSales))}</td><td>{formatMoney(Number(x.vat))}</td><td>{formatMoney(Number(x.grossProfit))}</td></tr>)}</tbody></table></div>:null}</Panel><ReportButtons from={from} to={to}/></>}
function ReportButtons({from,to}:{from:string;to:string}){const download=async(name:string,load:()=>Promise<Array<Record<string,string|number|undefined>>>)=>exportCsv(name,await load());return <Panel title="التقارير التشغيلية الجاهزة"><div className="row-actions"><button className="btn" onClick={async()=>exportCsv("product-profitability",productProfitability(await db.saleOrders.toArray()))}>ربحية المنتجات</button><button className="btn" onClick={()=>download("supplier-aging",supplierAging)}>أعمار الموردين</button><button className="btn" onClick={()=>download("stock-movements",()=>stockMovementReport({from,to}))}>حركات المخزون</button><button className="btn" onClick={()=>download("waste",()=>wasteReport({from,to}))}>الهالك</button><button className="btn" onClick={()=>download("production",()=>productionReport({from,to}))}>التصنيع</button><button className="btn" onClick={()=>download("shifts",()=>shiftReport({from,to}))}>الورديات</button><button className="btn" onClick={()=>download("purchases",()=>purchaseReport({from,to}))}>المشتريات</button><button className="btn" onClick={()=>download("expenses",()=>expenseReport({from,to}))}>المصروفات</button></div></Panel>}

function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><h3>{title}</h3></div><div className="panel-body">{children}</div></section>}
function Row({title,text,actions}:{title:string;text:string;actions?:React.ReactNode}){return <div className="rank-row"><div><strong>{title}</strong><small className="cell-sub">{text}</small></div><div className="row-actions">{actions}</div></div>}
function Empty({text}:{text:string}){return <p className="cell-sub">{text}</p>}
function status(x:string){return x.replaceAll("_"," ")}
