"use client";

import { db } from "@/src/db/database";
import type { AccountingAccount, CashAccount, CashierShift, JournalEntry, JournalLine, PurchaseInvoice, PurchaseInvoiceLine, RestaurantExpense, Supplier, SupplierPayment } from "./models";
import { buildCashTransferLines, buildExpenseLines, buildProductionLines, buildPurchaseJournalLines, buildSaleLines, buildShiftDifferenceLines, buildStockTransferLines, buildSupplierPaymentLines, type PostingLineSpec, validateJournalLines } from "./accounting-rules";
import { convertUnitQuantity } from "@/src/lib/units";
import { multiplyMoney, roundQuantity } from "@/src/lib/money";

const stamp = () => new Date().toISOString();
const uid = () => crypto.randomUUID();
const audit = () => ({ createdAt: stamp(), updatedAt: stamp(), createdBy: "local-admin" });

const accountRows: Array<[string, string, string, string | undefined, AccountingAccount["type"]]> = [
  ["1000","الأصول","Assets",undefined,"asset"],["1100","النقد وما في حكمه","Cash and Equivalents","1000","asset"],["1110","الخزينة الرئيسية","Main Cash","1100","asset"],["1120","خزينة الكاشير","Cashier Cash","1100","asset"],["1130","البنك","Bank","1100","asset"],["1140","تسوية البطاقات","Card Clearing","1100","asset"],["1150","تسوية المحافظ الإلكترونية","Wallet Clearing","1100","asset"],["1200","المخزون","Inventory","1000","asset"],["1210","مخزون المواد الخام","Raw Materials Inventory","1200","asset"],["1220","مخزون المطبخ وتحت التشغيل","Kitchen / WIP Inventory","1200","asset"],["1230","مخزون المنتج التام","Finished Goods Inventory","1200","asset"],["1300","العملاء","Accounts Receivable","1000","asset"],["1400","مصروفات مقدمة","Prepaid Expenses","1000","asset"],["1500","الأصول الثابتة","Fixed Assets","1000","asset"],["1510","معدات المطبخ","Kitchen Equipment","1500","asset"],["1520","ثلاجات","Refrigerators","1500","asset"],["1530","ماكينات القهوة","Coffee Machines","1500","asset"],["1540","معدات نقاط البيع","POS Equipment","1500","asset"],["1550","أثاث","Furniture","1500","asset"],["1590","مجمع الإهلاك","Accumulated Depreciation","1500","asset"],
  ["2000","الالتزامات","Liabilities",undefined,"liability"],["2100","الدائنون","Accounts Payable","2000","liability"],["2110","الموردون","Suppliers","2100","liability"],["2190","ضريبة مدخلات","Input VAT","2000","asset"],["2200","ضريبة القيمة المضافة المستحقة","VAT Payable","2000","liability"],["2300","رواتب مستحقة","Accrued Salaries","2000","liability"],["2400","مصروفات مستحقة أخرى","Other Accrued Expenses","2000","liability"],["2500","قروض","Loans","2000","liability"],
  ["3000","حقوق الملكية","Equity",undefined,"equity"],["3100","رأس مال المالك","Owner Capital","3000","equity"],["3200","أرباح محتجزة","Retained Earnings","3000","equity"],["3300","ربح العام الحالي","Current Year Profit","3000","equity"],
  ["4000","الإيرادات","Revenue",undefined,"revenue"],["4100","مبيعات الطعام","Food Sales","4000","revenue"],["4200","مبيعات المشروبات","Beverage Sales","4000","revenue"],["4300","مبيعات التوصيل","Delivery Sales","4000","revenue"],["4400","إيراد رسوم الخدمة","Service Charge Revenue","4000","revenue"],["4500","إيرادات تشغيل أخرى","Other Operating Revenue","4000","revenue"],["4600","خصومات المبيعات","Sales Discounts","4000","contra_revenue"],["4700","مرتجعات المبيعات","Sales Returns","4000","contra_revenue"],
  ["5000","تكلفة المبيعات","Cost of Sales",undefined,"cost_of_sales"],["5100","تكلفة الطعام","Food Cost","5000","cost_of_sales"],["5200","تكلفة المشروبات","Beverage Cost","5000","cost_of_sales"],["5300","تكلفة التعبئة","Packaging Cost","5000","cost_of_sales"],["5400","هالك الإنتاج","Production Waste","5000","cost_of_sales"],
  ["6000","مصروفات التشغيل","Operating Expenses",undefined,"expense"],["6110","الإيجار","Rent","6000","expense"],["6120","الكهرباء","Electricity","6000","expense"],["6130","المياه","Water","6000","expense"],["6140","الغاز","Gas","6000","expense"],["6150","الرواتب والأجور","Salaries and Wages","6000","expense"],["6160","الإنترنت","Internet","6000","expense"],["6170","الصيانة","Maintenance","6000","expense"],["6180","النظافة","Cleaning","6000","expense"],["6190","مصروف التعبئة","Packaging Expense","6000","expense"],["6200","التسويق","Marketing","6000","expense"],["6210","عمولة منصات التوصيل","Delivery Platform Commission","6000","expense"],["6220","رسوم البنوك والدفع","Bank / Payment Fees","6000","expense"],["6230","النقل","Transportation","6000","expense"],["6240","مصروفات إدارية","Administrative Expenses","6000","expense"],["6250","مصروف الإهلاك","Depreciation Expense","6000","expense"],["6260","فروق المخزون","Inventory Variance","6000","expense"],["6270","عجز الكاشير","Cashier Shortage","6000","expense"],["6280","مصروفات أخرى","Other Expenses","6000","expense"],
  ["7000","إيرادات أخرى","Other Income",undefined,"other_income"],["7100","فائض الكاشير","Cashier Surplus","7000","other_income"],
];

export async function ensureDefaultAccountingSetup() {
  await db.transaction("rw", [db.accounts, db.cashAccounts], async () => {
    const existing = await db.accounts.toArray(); const byCode = new Map(existing.map((account) => [account.code, account]));
    for (const [code, nameAr, nameEn, parentCode, type] of accountRows) if (!byCode.has(code)) { const account: AccountingAccount = { id: `acc-${code}`, code, nameAr, nameEn, parentId: parentCode ? `acc-${parentCode}` : undefined, type, active: true, system: true, ...audit() }; await db.accounts.put(account); }
    const cashRows: Array<[string,string,CashAccount["type"],string]> = [["MAIN-CASH","الخزينة الرئيسية","cash","1110"],["CASHIER-CASH","خزينة الكاشير","cash","1120"],["BANK","الحساب البنكي","bank","1130"],["CARD","تسوية البطاقات","card_clearing","1140"],["WALLET","تسوية المحافظ","wallet_clearing","1150"]];
    for (const [code, nameAr, type, accountCode] of cashRows) if (!(await db.cashAccounts.where("code").equals(code).first())) await db.cashAccounts.put({ id: `cash-${code.toLowerCase()}`, code, nameAr, type, ledgerAccountId: `acc-${accountCode}`, openingBalancePiasters: 0, active: true, ...audit() });
  });
}

export async function setAccountActive(accountId:string, active:boolean) { const account=await db.accounts.get(accountId); if(!account) throw new Error("الحساب غير موجود"); await db.accounts.update(accountId,{active,updatedAt:stamp()}); }

async function accountId(code: string) { const account = await db.accounts.where("code").equals(code).first(); if (!account) throw new Error(`الحساب ${code} غير موجود`); return account.id; }

export async function createJournal(input: { date?: string; referenceType: string; referenceId: string; referenceNumber: string; description: string; sourceModule: string; lines: PostingLineSpec[] }) {
  validateJournalLines(input.lines); const existing = await db.journalEntries.where("[referenceType+referenceId]").equals([input.referenceType, input.referenceId]).first(); if (existing) return existing;
  const timestamp = stamp(); const entry: JournalEntry = { id: uid(), entryNumber: `JE-${Date.now().toString().slice(-9)}`, date: input.date ?? timestamp.slice(0,10), referenceType: input.referenceType, referenceId: input.referenceId, referenceNumber: input.referenceNumber, description: input.description, status: "posted", postedAt: timestamp, createdAt: timestamp, updatedAt: timestamp, createdBy: "accounting-engine" };
  const lines: JournalLine[] = []; for (const spec of input.lines) lines.push({ id: uid(), journalEntryId: entry.id, accountId: await accountId(spec.accountCode), debitMinor: spec.debitMinor, creditMinor: spec.creditMinor, description: spec.description, sourceModule: input.sourceModule });
  await db.journalEntries.put(entry); await db.journalLines.bulkPut(lines); return entry;
}

export async function postInventoryReceipt(referenceId: string, referenceNumber: string, valueMinor: number) { return createJournal({ referenceType:"inventory_receipt", referenceId, referenceNumber, description:"إضافة رصيد افتتاحي للمخزون", sourceModule:"inventory", lines:[{accountCode:"1210",debitMinor:valueMinor,creditMinor:0,description:"مخزون خام"},{accountCode:"3100",debitMinor:0,creditMinor:valueMinor,description:"رصيد افتتاحي"}] }); }
export async function postInventoryToKitchenTransfer(referenceId: string, referenceNumber: string, valueMinor: number) { return createJournal({ referenceType:"kitchen_transfer", referenceId, referenceNumber, description:"تحويل مخزون إلى المطبخ", sourceModule:"inventory", lines:buildStockTransferLines(valueMinor) }); }
export async function postProductionOrder(referenceId: string, referenceNumber: string, valueMinor: number) { return createJournal({ referenceType:"production", referenceId, referenceNumber, description:"تحويل تكلفة الإنتاج إلى المنتج التام", sourceModule:"production", lines:buildProductionLines(valueMinor) }); }
export async function postSaleOrder(referenceId: string, referenceNumber: string, subtotalMinor: number, vatMinor: number, totalMinor: number, cogsMinor: number, paymentMethod: "cash"|"card"|"wallet") { const paymentCode={cash:"1120",card:"1140",wallet:"1150"}[paymentMethod]; return createJournal({ referenceType:"sale", referenceId, referenceNumber, description:"مبيعات الكاشير وتكلفتها", sourceModule:"cashier", lines:buildSaleLines({subtotalMinor,vatMinor,totalMinor,cogsMinor,paymentAccountCode:paymentCode}) }); }

export async function postExpense(expense: RestaurantExpense, expenseAccountCode: string, paymentAccountCode: string) { return createJournal({ date:expense.expenseDate, referenceType:"expense", referenceId:expense.id, referenceNumber:expense.reference || `EXP-${expense.id.slice(0,6)}`, description:expense.description, sourceModule:"expenses", lines:buildExpenseLines({expenseAccountCode, amountMinor:expense.amountPiasters, vatMinor:expense.vatPiasters ?? 0, paymentAccountCode}) }); }

export async function createExpense(input: Omit<RestaurantExpense,"id"|"createdAt"|"updatedAt"|"createdBy"> & { expenseAccountCode:string; paymentAccountCode:string }) { return db.transaction("rw", [db.expenses,db.accounts,db.journalEntries,db.journalLines], async()=>{ const { expenseAccountCode, paymentAccountCode, ...payload } = input; const expense:RestaurantExpense={...payload,id:uid(),...audit()}; await db.expenses.add(expense); await postExpense(expense,expenseAccountCode,paymentAccountCode); return expense; }); }

export async function createSupplier(input: Omit<Supplier,"id"|"createdAt"|"updatedAt"|"createdBy">) { const supplier={...input,id:uid(),...audit()}; await db.suppliers.add(supplier); if(input.openingBalancePiasters>0) await db.transaction("rw",[db.accounts,db.journalEntries,db.journalLines],()=>createJournal({referenceType:"supplier_opening",referenceId:supplier.id,referenceNumber:supplier.code,description:`رصيد افتتاحي ${supplier.name}`,sourceModule:"suppliers",lines:[{accountCode:"3100",debitMinor:input.openingBalancePiasters,creditMinor:0,description:"مقابل رصيد افتتاحي"},{accountCode:"2110",debitMinor:0,creditMinor:input.openingBalancePiasters,description:"رصيد المورد"}]})); return supplier; }

export async function postPurchase(input:{ invoice: Omit<PurchaseInvoice,"id"|"subtotalPiasters"|"vatPiasters"|"totalPiasters"|"status"|"createdAt"|"updatedAt"|"createdBy">; lines:Array<Omit<PurchaseInvoiceLine,"id"|"purchaseInvoiceId"|"subtotalPiasters"|"vatPiasters"|"lineTotalPiasters">> }) {
  return db.transaction("rw",[db.purchaseInvoices,db.purchaseInvoiceLines,db.suppliers,db.accounts,db.journalEntries,db.journalLines,db.units,db.items,db.balances,db.movements],async()=>{
    if(!input.lines.length) throw new Error("أضف بند مشتريات واحدًا على الأقل"); const id=uid(); let subtotal=0,vat=0; const savedLines:PurchaseInvoiceLine[]=[]; const sign=input.invoice.kind==="return"?-1:1;
    for(const raw of input.lines){ const item=await db.items.get(raw.itemId),unit=await db.units.get(raw.unitId),base=item?await db.units.get(item.baseUnitId):undefined;if(!item||!unit||!base)throw new Error("بيانات بند المشتريات غير مكتملة");if(unit.family!==base.family)throw new Error("وحدة المشتريات غير متوافقة");const quantityBase=convertUnitQuantity(raw.quantity,unit.baseFactor,base.baseFactor);const lineSubtotal=multiplyMoney(raw.unitCostPiasters,raw.quantity);const lineVat=Math.round(lineSubtotal*raw.vatRate/100);subtotal+=lineSubtotal;vat+=lineVat;const balance=await db.balances.get(`${input.invoice.warehouseId}:${item.id}`)??{id:`${input.invoice.warehouseId}:${item.id}`,warehouseId:input.invoice.warehouseId,itemId:item.id,quantity:0,reserved:0,averageCostPiasters:item.averageCostPiasters,updatedAt:stamp()};if(sign<0&&balance.quantity<quantityBase)throw new Error(`رصيد ${item.nameAr} لا يكفي للمرتجع`);const newQty=roundQuantity(balance.quantity+sign*quantityBase);const oldValue=multiplyMoney(balance.averageCostPiasters,balance.quantity);const newAverage=sign>0&&newQty?Math.round((oldValue+lineSubtotal)/newQty):balance.averageCostPiasters;await db.balances.put({...balance,quantity:newQty,averageCostPiasters:newAverage,updatedAt:stamp()});await db.items.update(item.id,{averageCostPiasters:newAverage,updatedAt:stamp()});await db.movements.add({id:uid(),warehouseId:input.invoice.warehouseId,itemId:item.id,type:sign>0?"purchase":"adjustment",quantity:sign*quantityBase,enteredQuantity:raw.quantity,enteredUnitId:raw.unitId,unitCostPiasters:Math.round(lineSubtotal/quantityBase),totalCostPiasters:sign*lineSubtotal,reference:input.invoice.invoiceNumber,note:input.invoice.notes,createdAt:stamp(),updatedAt:stamp(),createdBy:"purchases"});savedLines.push({...raw,id:uid(),purchaseInvoiceId:id,subtotalPiasters:lineSubtotal,vatPiasters:lineVat,lineTotalPiasters:lineSubtotal+lineVat}); }
    const total=subtotal+vat;const paid=input.invoice.paymentType==="cash"?total:input.invoice.paymentType==="credit"?0:Math.min(input.invoice.paidPiasters,total);const invoice:PurchaseInvoice={...input.invoice,id,paidPiasters:paid,subtotalPiasters:subtotal,vatPiasters:vat,totalPiasters:total,status:"posted",...audit()};await db.purchaseInvoices.add(invoice);await db.purchaseInvoiceLines.bulkAdd(savedLines);const paymentCode=input.invoice.paymentAccountId?(await db.accounts.get(input.invoice.paymentAccountId))?.code:"1110";await createJournal({date:invoice.date,referenceType:"purchase",referenceId:id,referenceNumber:invoice.invoiceNumber,description:invoice.kind==="return"?"مرتجع مشتريات":"فاتورة مشتريات",sourceModule:"purchases",lines:buildPurchaseJournalLines({inventoryMinor:subtotal,vatMinor:vat,paidMinor:paid,totalMinor:total,paymentAccountCode:paymentCode,isReturn:invoice.kind==="return"})});return invoice;
  });
}

export async function paySupplier(input:Omit<SupplierPayment,"id"|"createdAt"|"updatedAt"|"createdBy">){return db.transaction("rw",[db.supplierPayments,db.accounts,db.journalEntries,db.journalLines],async()=>{const payment:SupplierPayment={...input,id:uid(),...audit()};await db.supplierPayments.add(payment);const code=(await db.accounts.get(input.paymentAccountId))?.code??"1110";await createJournal({date:input.date,referenceType:"supplier_payment",referenceId:payment.id,referenceNumber:input.reference,description:"سداد مورد",sourceModule:"suppliers",lines:buildSupplierPaymentLines(input.amountPiasters,code)});return payment;});}

export async function transferCash(input:{fromCashAccountId:string;toCashAccountId:string;amountPiasters:number;date:string;reference?:string;notes?:string}){return db.transaction("rw",[db.cashTransfers,db.cashAccounts,db.accounts,db.journalEntries,db.journalLines],async()=>{const from=await db.cashAccounts.get(input.fromCashAccountId),to=await db.cashAccounts.get(input.toCashAccountId);if(!from||!to||from.id===to.id||input.amountPiasters<=0)throw new Error("بيانات التحويل غير صحيحة");const [fromLedger,toLedger]=await Promise.all([db.accounts.get(from.ledgerAccountId),db.accounts.get(to.ledgerAccountId)]);if(!fromLedger||!toLedger)throw new Error("حساب التحويل غير موجود");const transfer={...input,id:uid(),number:`CT-${Date.now().toString().slice(-8)}`,...audit()};await db.cashTransfers.add(transfer);await createJournal({date:input.date,referenceType:"cash_transfer",referenceId:transfer.id,referenceNumber:transfer.number,description:`تحويل من ${from.nameAr} إلى ${to.nameAr}`,sourceModule:"cash_bank",lines:buildCashTransferLines(input.amountPiasters,fromLedger.code,toLedger.code)});return transfer;});}

export async function openShift(cashier:string,openingCashPiasters:number){const existing=await db.shifts.where("status").equals("open").first();if(existing)throw new Error("توجد وردية مفتوحة بالفعل");const shift:CashierShift={id:uid(),number:`SH-${Date.now().toString().slice(-8)}`,cashier,openedAt:stamp(),openingCashPiasters,cashSalesPiasters:0,cardSalesPiasters:0,walletSalesPiasters:0,cashRefundsPiasters:0,cashPaidOutsPiasters:0,expectedCashPiasters:openingCashPiasters,status:"open",...audit()};await db.shifts.add(shift);await db.settings.update("settings",{activeShift:true});return shift;}
export async function closeShift(shiftId:string,actualCashPiasters:number){return db.transaction("rw",[db.shifts,db.saleOrders,db.settings,db.accounts,db.journalEntries,db.journalLines],async()=>{const shift=await db.shifts.get(shiftId);if(!shift||shift.status!=="open")throw new Error("الوردية غير مفتوحة");const sales=(await db.saleOrders.where("createdAt").aboveOrEqual(shift.openedAt).toArray());const cash=sales.filter(x=>x.paymentMethod==="cash").reduce((s,x)=>s+x.totalPiasters,0),card=sales.filter(x=>x.paymentMethod==="card").reduce((s,x)=>s+x.totalPiasters,0),wallet=sales.filter(x=>x.paymentMethod==="wallet").reduce((s,x)=>s+x.totalPiasters,0);const expected=shift.openingCashPiasters+cash-shift.cashRefundsPiasters-shift.cashPaidOutsPiasters;const difference=actualCashPiasters-expected;await db.shifts.update(shift.id,{closedAt:stamp(),cashSalesPiasters:cash,cardSalesPiasters:card,walletSalesPiasters:wallet,expectedCashPiasters:expected,actualCashPiasters,differencePiasters:difference,status:"closed",updatedAt:stamp()});if(difference)await createJournal({referenceType:difference<0?"shift_shortage":"shift_surplus",referenceId:shift.id,referenceNumber:shift.number,description:difference<0?"عجز إغلاق وردية":"فائض إغلاق وردية",sourceModule:"shifts",lines:buildShiftDifferenceLines(difference)});await db.settings.update("settings",{activeShift:false});return {...shift,expectedCashPiasters:expected,actualCashPiasters,differencePiasters:difference,status:"closed" as const};});}

export async function reverseJournalEntry(entryId:string){return db.transaction("rw",[db.accounts,db.journalEntries,db.journalLines],async()=>{const original=await db.journalEntries.get(entryId);if(!original||original.status!=="posted")throw new Error("القيد غير قابل للعكس");const originalLines=await db.journalLines.where("journalEntryId").equals(entryId).toArray();const specs:PostingLineSpec[]=[];for(const item of originalLines){const account=await db.accounts.get(item.accountId);if(!account)throw new Error("حساب القيد غير موجود");specs.push({accountCode:account.code,debitMinor:item.creditMinor,creditMinor:item.debitMinor,description:`عكس: ${item.description}`});}const reversal=await createJournal({referenceType:"journal_reversal",referenceId:original.id,referenceNumber:`REV-${original.entryNumber}`,description:`عكس ${original.description}`,sourceModule:"journal",lines:specs});await db.journalEntries.update(original.id,{status:"reversed",reversedEntryId:reversal.id,updatedAt:stamp()});return reversal;});}
