"use client";
import {db} from "@/src/db/database";import type {Approval,UserRole} from "./models";import {requirePermission} from "./authorization-service";
const uid=()=>crypto.randomUUID(),stamp=()=>new Date().toISOString();
export async function requestApproval(input:{entityType:string;entityId:string;reference:string;requestedBy:string;amountPiasters?:number;payload?:string;notes?:string}){const row:Approval={id:uid(),...input,requestedAt:stamp(),status:"pending",createdAt:stamp(),updatedAt:stamp(),createdBy:input.requestedBy};await db.approvals.add(row);return row;}
export async function requestJournalReversal(input:{entryId:string;role:UserRole;user:string;reason:string}){await requirePermission(input.role,"accounting.reverse");const entry=await db.journalEntries.get(input.entryId);if(!entry||entry.status!=="posted")throw new Error("القيد غير قابل للعكس");return requestApproval({entityType:"journal_reversal",entityId:entry.id,reference:entry.entryNumber,requestedBy:input.user,payload:JSON.stringify({entryId:entry.id}),notes:input.reason});}
export async function requestSaleRefundApproval(input:{saleId:string;reference:string;amountPiasters:number;role:UserRole;user:string;reason:string}){await requirePermission(input.role,"cashier.refund");return requestApproval({entityType:"sale_refund",entityId:input.saleId,reference:input.reference,requestedBy:input.user,amountPiasters:input.amountPiasters,payload:JSON.stringify({saleId:input.saleId,reason:input.reason}),notes:input.reason});}
export async function requestLargeDiscountApproval(input:{saleId:string;reference:string;discountPercent:number;role:UserRole;user:string;reason:string}){await requirePermission(input.role,"cashier.discount");return requestApproval({entityType:"large_discount",entityId:input.saleId,reference:input.reference,requestedBy:input.user,payload:JSON.stringify({saleId:input.saleId,discountPercent:input.discountPercent,reason:input.reason}),notes:input.reason});}
export async function decideApproval(id:string,decision:"approved"|"rejected",role:UserRole,user:string,reason?:string){await requirePermission(role,"approvals.decide");const row=await db.approvals.get(id);if(!row||row.status!=="pending")throw new Error("طلب الموافقة غير متاح");if(row.requestedBy===user)throw new Error("لا يمكن لمنشئ الطلب اعتماد طلبه");const time=stamp();if(decision==="approved"&&row.payload){const payload=JSON.parse(row.payload) as Record<string,unknown>;if(["waste","stock_count_variance","shift_difference"].includes(row.entityType)){const operations=await import("./operations-service");if(row.entityType==="waste")await operations.postWaste(payload as Parameters<typeof operations.postWaste>[0]);if(row.entityType==="stock_count_variance")await operations.approveStockCount(String(payload.countId));if(row.entityType==="shift_difference")await operations.closeShiftControlled(String(payload.shiftId),Number(payload.actualCashPiasters));}if(row.entityType==="journal_reversal"){const accounting=await import("./accounting-service");await accounting.reverseJournalEntry(String(payload.entryId));}}
  await db.transaction("rw",[db.approvals,db.purchaseRequests,db.procurementOrders,db.auditLogs],async()=>{await db.approvals.update(id,decision==="approved"?{status:decision,approvedBy:user,approvedAt:time,updatedAt:time}:{status:decision,rejectedBy:user,rejectedAt:time,rejectionReason:reason,updatedAt:time});if(row.entityType==="purchase_request")await db.purchaseRequests.update(row.entityId,{status:decision==="approved"?"approved":"rejected",updatedAt:time});if(row.entityType==="purchase_order")await db.procurementOrders.update(row.entityId,{status:decision==="approved"?"approved":"cancelled",updatedAt:time});await db.auditLogs.add({id:uid(),action:`approval_${decision}`,entityType:row.entityType,entityId:row.entityId,reference:row.reference,timestamp:time,localUser:user,module:"approvals",afterSummary:reason});});}
