"use client";
import {db} from "@/src/db/database";
const BACKUP_VERSION=3,SCHEMA_VERSION=7;
const tableNames=["units","items","warehouses","balances","recipes","movements","productionOrders","saleOrders","expenses","employees","attendanceRecords","payrollRecords","accounts","journalEntries","journalLines","suppliers","purchaseInvoices","purchaseInvoiceLines","supplierPayments","cashAccounts","cashTransfers","shifts","shiftCashMovements","stockCounts","stockCountLines","wasteEntries","auditLogs","alerts","users","rolePermissions","approvals","purchaseRequests","purchaseRequestLines","procurementOrders","procurementOrderLines","goodsReceipts","goodsReceiptLines","supplierInvoiceRecords","supplierInvoiceRecordLines","supplierInvoicePaymentAllocations","purchaseReturnRecords","settings"] as const;
type Backup={backupVersion:number;schemaVersion:number;applicationVersion:string;createdAt:string;restaurantName:string;manifest:Array<{table:string;count:number}>;tables:Record<string,Array<Record<string,unknown>>>};
async function snapshot(includeSecrets=false):Promise<Backup>{const tables:Backup["tables"]={};for(const name of tableNames){const rows=await db.table<Record<string,unknown>,string>(name).toArray();tables[name]=rows.map(row=>{if(!includeSecrets&&name==="settings"){const {passwordHash,...safe}=row;void passwordHash;return safe}if(!includeSecrets&&name==="users"){const {passwordHash,...safe}=row;void passwordHash;return safe}return row});}const settings=await db.settings.get("settings");return{backupVersion:BACKUP_VERSION,schemaVersion:SCHEMA_VERSION,applicationVersion:"0.2.0",createdAt:new Date().toISOString(),restaurantName:settings?.restaurantName??"RestaurantFlow",manifest:tableNames.map(table=>({table,count:tables[table].length})),tables};}
export async function createBackup(){const backup=await snapshot();await db.auditLogs.add({id:crypto.randomUUID(),action:"backup_create",entityType:"backup",entityId:backup.createdAt,reference:backup.createdAt,timestamp:backup.createdAt,localUser:"local-admin",afterSummary:`tables=${backup.manifest.length}`});return backup;}
export function validateBackup(value:unknown){if(!value||typeof value!=="object")throw new Error("ملف النسخة الاحتياطية غير صالح");const backup=value as Partial<Backup>;if(backup.backupVersion!==BACKUP_VERSION||backup.schemaVersion!==SCHEMA_VERSION||!backup.tables)throw new Error("إصدار النسخة غير مدعوم");for(const name of tableNames)if(!Array.isArray(backup.tables[name]))throw new Error(`الجدول ${name} مفقود أو تالف`);for(const [name,rows] of Object.entries(backup.tables)){const ids=new Set<string>();for(const row of rows){if(!row||typeof row!=="object")throw new Error(`سجل تالف في ${name}`);const id=row.id;if(typeof id!=="string"||!id)throw new Error(`معرف مفقود في ${name}`);if(ids.has(id))throw new Error(`معرف مكرر في ${name}`);ids.add(id);for(const [key,field] of Object.entries(row))if((key.toLowerCase().includes("quantity")||key.toLowerCase().includes("piasters"))&&typeof field!=="number")throw new Error(`قيمة رقمية تالفة في ${name}.${key}`);}}
  const ids=(name:string)=>new Set(backup.tables![name].map(x=>String(x.id))),items=ids("items"),warehouses=ids("warehouses"),units=ids("units"),suppliers=ids("suppliers");
  for(const row of backup.tables.balances)if(!items.has(String(row.itemId))||!warehouses.has(String(row.warehouseId)))throw new Error("علاقة رصيد مخزون غير صالحة");
  for(const row of backup.tables.purchaseRequestLines)if(!items.has(String(row.itemId))||!units.has(String(row.unitId)))throw new Error("علاقة بند طلب شراء غير صالحة");
  for(const row of backup.tables.supplierInvoiceRecords)if(!suppliers.has(String(row.supplierId)))throw new Error("علاقة فاتورة مورد غير صالحة");
  for(const row of backup.tables.items)if(row.imageDataUrl!==undefined&&(typeof row.imageDataUrl!=="string"||!row.imageDataUrl.startsWith("data:image/")))throw new Error("صورة صنف غير صالحة");
  for(const row of backup.tables.settings)if(row.logoDataUrl!==undefined&&(typeof row.logoDataUrl!=="string"||!row.logoDataUrl.startsWith("data:image/")))throw new Error("شعار المطعم غير صالح");
  return backup as Backup;}
export async function restoreBackup(value:unknown){const backup=validateBackup(value),safety=await snapshot(true),settingsSecret=(await db.settings.get("settings"))?.passwordHash,userSecrets=new Map((await db.users.toArray()).map(x=>[x.username,x.passwordHash]));const imported:Backup={...backup,tables:{...backup.tables,settings:backup.tables.settings.map(x=>({...x,passwordHash:settingsSecret})),users:backup.tables.users.map(x=>({...x,passwordHash:userSecrets.get(String(x.username))??"",active:Boolean(userSecrets.get(String(x.username)))&&x.active!==false}))}};try{await db.transaction("rw",tableNames.map(name=>db.table(name)),async()=>{for(const name of [...tableNames].reverse())await db.table(name).clear();for(const name of tableNames)if(imported.tables[name].length)await db.table(name).bulkAdd(imported.tables[name]);});await db.auditLogs.add({id:crypto.randomUUID(),action:"backup_restore",entityType:"backup",entityId:backup.createdAt,reference:backup.createdAt,timestamp:new Date().toISOString(),localUser:"local-admin",module:"backup",afterSummary:`restaurant=${backup.restaurantName}`});return{backup,safety};}catch(error){await db.transaction("rw",tableNames.map(name=>db.table(name)),async()=>{for(const name of [...tableNames].reverse())await db.table(name).clear();for(const name of tableNames)if(safety.tables[name].length)await db.table(name).bulkAdd(safety.tables[name]);});throw error;}}
export function downloadBackup(backup:Backup){const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`restaurantflow-backup-${backup.createdAt.slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);}
export {tableNames as backupTableNames};
