"use client";
import {db} from "@/src/db/database";
import type {GoodsReceipt,GoodsReceiptLine,ProcurementOrder,ProcurementOrderLine,PurchaseRequest,PurchaseRequestLine,PurchaseReturnRecord,SupplierInvoiceRecord,SupplierInvoiceRecordLine,SupplierPayment,UserRole} from "./models";
import {requirePermission} from "./authorization-service";
import {requestApproval} from "./approval-service";
import {addOpeningStock} from "./inventory-service";
import {createJournal} from "./accounting-service";
import {convertUnitQuantity} from "@/src/lib/units";
import {roundQuantity} from "@/src/lib/money";
import {writeAudit} from "./audit-service";

const uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),audit=(user:string)=>({createdAt:now(),updatedAt:now(),createdBy:user});
const num=async(prefix:string,table:{count:()=>Promise<number>})=>`${prefix}-${String(await table.count()+1).padStart(6,"0")}`;

export async function createPurchaseRequest(input:{role:UserRole;user:string;requiredDate:string;warehouseId:string;notes?:string;lines:Array<Omit<PurchaseRequestLine,"id"|"purchaseRequestId">>}){
  await requirePermission(input.role,"purchases.request");if(!input.lines.length||input.lines.some(x=>x.requestedQuantity<=0))throw new Error("أضف كمية شراء صحيحة");
  return db.transaction("rw",[db.purchaseRequests,db.purchaseRequestLines,db.auditLogs],async()=>{const row:PurchaseRequest={id:uid(),number:await num("PR",db.purchaseRequests),requestDate:now().slice(0,10),requestedBy:input.user,requiredDate:input.requiredDate,warehouseId:input.warehouseId,notes:input.notes,status:"draft",...audit(input.user)};await db.purchaseRequests.add(row);await db.purchaseRequestLines.bulkAdd(input.lines.map(x=>({...x,id:uid(),purchaseRequestId:row.id})));await writeAudit({action:"purchase_request_create",entityType:"purchase_request",entityId:row.id,reference:row.number,user:input.user,module:"purchasing",afterSummary:`lines=${input.lines.length}`});return row;});
}

export async function submitPurchaseRequest(id:string,role:UserRole,user:string){await requirePermission(role,"purchases.request");const row=await db.purchaseRequests.get(id);if(!row||row.status!=="draft")throw new Error("طلب الشراء غير قابل للإرسال");await db.transaction("rw",[db.purchaseRequests,db.approvals],async()=>{await db.purchaseRequests.update(id,{status:"pending_approval",updatedAt:now()});await requestApproval({entityType:"purchase_request",entityId:id,reference:row.number,requestedBy:user});});}

export async function createPurchaseOrder(input:{role:UserRole;user:string;requestId?:string;supplierId:string;warehouseId:string;expectedDeliveryDate:string;paymentTerms?:string;notes?:string;lines:Array<Omit<ProcurementOrderLine,"id"|"purchaseOrderId"|"receivedQuantity"|"lineTotalPiasters">>}){
  await requirePermission(input.role,"purchases.create_order");if(input.requestId){const request=await db.purchaseRequests.get(input.requestId);if(!request||request.status!=="approved")throw new Error("طلب الشراء غير معتمد");}
  return db.transaction("rw",[db.procurementOrders,db.procurementOrderLines,db.purchaseRequests,db.auditLogs],async()=>{let subtotal=0,discount=0,vat=0;const id=uid(),lines=input.lines.map(x=>{const before=x.orderedQuantity*x.unitPricePiasters,net=before-x.discountPiasters,tax=Math.round(net*x.vatRate/100);subtotal+=before;discount+=x.discountPiasters;vat+=tax;return{...x,id:uid(),purchaseOrderId:id,receivedQuantity:0,lineTotalPiasters:net+tax}});const row:ProcurementOrder={id,number:await num("PO",db.procurementOrders),requestId:input.requestId,supplierId:input.supplierId,orderDate:now().slice(0,10),expectedDeliveryDate:input.expectedDeliveryDate,warehouseId:input.warehouseId,paymentTerms:input.paymentTerms,notes:input.notes,status:"draft",subtotalPiasters:subtotal,discountPiasters:discount,vatPiasters:vat,totalPiasters:subtotal-discount+vat,...audit(input.user)};await db.procurementOrders.add(row);await db.procurementOrderLines.bulkAdd(lines);if(input.requestId)await db.purchaseRequests.update(input.requestId,{status:"converted",updatedAt:now()});await writeAudit({action:"purchase_order_create",entityType:"purchase_order",entityId:row.id,reference:row.number,user:input.user,module:"purchasing",afterSummary:`total=${row.totalPiasters}`});return row;});
}

export async function submitPurchaseOrder(id:string,role:UserRole,user:string){await requirePermission(role,"purchases.create_order");const row=await db.procurementOrders.get(id);if(!row||row.status!=="draft")throw new Error("أمر الشراء غير قابل للإرسال");await db.transaction("rw",[db.procurementOrders,db.approvals],async()=>{await db.procurementOrders.update(id,{status:"pending_approval",updatedAt:now()});await requestApproval({entityType:"purchase_order",entityId:id,reference:row.number,requestedBy:user,notes:`القيمة ${row.totalPiasters}`});});}

export async function postGoodsReceipt(input:{role:UserRole;user:string;purchaseOrderId:string;notes?:string;lines:Array<{purchaseOrderLineId:string;quantity:number}>}){
  await requirePermission(input.role,"purchases.receive");const po=await db.procurementOrders.get(input.purchaseOrderId);if(!po||!["approved","partially_received"].includes(po.status))throw new Error("أمر الشراء غير معتمد");const poLines=await db.procurementOrderLines.where("purchaseOrderId").equals(po.id).toArray();const receiptId=uid(),number=await num("GRN",db.goodsReceipts);
  return db.transaction("rw",[db.goodsReceipts,db.goodsReceiptLines,db.procurementOrders,db.procurementOrderLines,db.units,db.items,db.warehouses,db.balances,db.movements,db.accounts,db.journalEntries,db.journalLines,db.auditLogs],async()=>{const saved:GoodsReceiptLine[]=[];for(const requested of input.lines){const line=poLines.find(x=>x.id===requested.purchaseOrderLineId);if(!line||requested.quantity<=0||line.receivedQuantity+requested.quantity>line.orderedQuantity)throw new Error("كمية الاستلام تتجاوز المتبقي في أمر الشراء");await addOpeningStock({warehouseId:po.warehouseId,itemId:line.itemId,quantity:requested.quantity,enteredUnitId:line.unitId,unitCostPiasters:line.unitPricePiasters,reference:number,note:`استلام ${po.number}`,skipAccounting:true});await db.procurementOrderLines.update(line.id,{receivedQuantity:line.receivedQuantity+requested.quantity});saved.push({id:uid(),goodsReceiptId:receiptId,purchaseOrderLineId:line.id,itemId:line.itemId,quantity:requested.quantity,unitId:line.unitId,unitCostPiasters:line.unitPricePiasters});}const receipt:GoodsReceipt={id:receiptId,number,purchaseOrderId:po.id,supplierId:po.supplierId,warehouseId:po.warehouseId,receiptDate:now().slice(0,10),receivedBy:input.user,notes:input.notes,status:"posted",...audit(input.user)};await db.goodsReceipts.add(receipt);await db.goodsReceiptLines.bulkAdd(saved);const updated=await db.procurementOrderLines.where("purchaseOrderId").equals(po.id).toArray();await db.procurementOrders.update(po.id,{status:updated.every(x=>x.receivedQuantity>=x.orderedQuantity)?"fully_received":"partially_received",updatedAt:now()});await writeAudit({action:"goods_receipt_post",entityType:"goods_receipt",entityId:receipt.id,reference:number,user:input.user,module:"purchasing",afterSummary:`po=${po.number};lines=${saved.length}`});return receipt;});
}

export async function postSupplierInvoice(input:{role:UserRole;user:string;supplierInvoiceNumber:string;supplierId:string;invoiceDate:string;dueDate:string;purchaseOrderId?:string;goodsReceiptId?:string;notes?:string;lines:Array<Omit<SupplierInvoiceRecordLine,"id"|"supplierInvoiceId"|"totalPiasters">>}){
  await requirePermission(input.role,"purchases.invoice");if(!input.goodsReceiptId)throw new Error("يجب ربط فاتورة المخزون بإيصال استلام");
  return db.transaction("rw",[db.supplierInvoiceRecords,db.supplierInvoiceRecordLines,db.goodsReceiptLines,db.accounts,db.journalEntries,db.journalLines,db.auditLogs],async()=>{let subtotal=0,discount=0,vat=0;const id=uid(),received=await db.goodsReceiptLines.where("goodsReceiptId").equals(input.goodsReceiptId!).toArray();const alreadyInvoices=await db.supplierInvoiceRecords.where("goodsReceiptId").equals(input.goodsReceiptId!).toArray();const alreadyLines=(await Promise.all(alreadyInvoices.map(x=>db.supplierInvoiceRecordLines.where("supplierInvoiceId").equals(x.id).toArray()))).flat();const lines=input.lines.map(x=>{const receivedQty=received.filter(r=>r.itemId===x.itemId&&r.unitId===x.unitId).reduce((s,r)=>s+r.quantity,0),invoicedQty=alreadyLines.filter(r=>r.itemId===x.itemId&&r.unitId===x.unitId).reduce((s,r)=>s+r.quantity,0);if(x.quantity<=0||invoicedQty+x.quantity>receivedQty)throw new Error("لا يمكن فوترة كمية لم يتم استلامها");const net=x.quantity*x.unitCostPiasters-x.discountPiasters,tax=Math.round(net*x.vatRate/100);subtotal+=x.quantity*x.unitCostPiasters;discount+=x.discountPiasters;vat+=tax;return{...x,id:uid(),supplierInvoiceId:id,totalPiasters:net+tax}});const total=subtotal-discount+vat,number=await num("PINV",db.supplierInvoiceRecords);const priceDifference=lines.some(line=>received.some(r=>r.itemId===line.itemId&&r.unitCostPiasters!==line.unitCostPiasters));const row:SupplierInvoiceRecord={id,number,supplierInvoiceNumber:input.supplierInvoiceNumber,supplierId:input.supplierId,invoiceDate:input.invoiceDate,dueDate:input.dueDate,purchaseOrderId:input.purchaseOrderId,goodsReceiptId:input.goodsReceiptId,subtotalPiasters:subtotal,discountPiasters:discount,vatPiasters:vat,totalPiasters:total,paidPiasters:0,matchingStatus:priceDifference?"price_difference":"matched",status:"unpaid",notes:input.notes,...audit(input.user)};await db.supplierInvoiceRecords.add(row);await db.supplierInvoiceRecordLines.bulkAdd(lines);await createJournal({date:row.invoiceDate,referenceType:"supplier_invoice",referenceId:id,referenceNumber:number,description:"إثبات فاتورة مورد",sourceModule:"purchasing",lines:[{accountCode:"1210",debitMinor:subtotal-discount,creditMinor:0,description:"قيمة المواد المستلمة"},{accountCode:"2190",debitMinor:vat,creditMinor:0,description:"ضريبة مدخلات"},{accountCode:"2110",debitMinor:0,creditMinor:total,description:"الموردون"}].filter(x=>x.debitMinor||x.creditMinor)});await writeAudit({action:"supplier_invoice_post",entityType:"supplier_invoice",entityId:id,reference:number,user:input.user,module:"purchasing",afterSummary:`total=${total};match=${row.matchingStatus}`});return row;});
}

export async function paySupplierInvoices(input:{role:UserRole;user:string;supplierId:string;date:string;paymentMethod:"cash"|"bank";paymentAccountId:string;reference?:string;notes?:string;allocations:Array<{supplierInvoiceId:string;amountPiasters:number}>}){
  await requirePermission(input.role,"purchases.pay");const amount=input.allocations.reduce((s,x)=>s+x.amountPiasters,0);if(amount<=0)throw new Error("قيمة السداد غير صحيحة");
  return db.transaction("rw",[db.supplierPayments,db.supplierInvoicePaymentAllocations,db.supplierInvoiceRecords,db.accounts,db.journalEntries,db.journalLines,db.auditLogs],async()=>{for(const allocation of input.allocations){const invoice=await db.supplierInvoiceRecords.get(allocation.supplierInvoiceId);if(!invoice||invoice.supplierId!==input.supplierId||allocation.amountPiasters<=0||invoice.paidPiasters+allocation.amountPiasters>invoice.totalPiasters)throw new Error("توزيع السداد يتجاوز المبلغ المستحق");}const payment:SupplierPayment={id:uid(),supplierId:input.supplierId,date:input.date,amountPiasters:amount,paymentMethod:input.paymentMethod,paymentAccountId:input.paymentAccountId,reference:input.reference||await num("PAY",db.supplierPayments),notes:input.notes,...audit(input.user)};await db.supplierPayments.add(payment);await db.supplierInvoicePaymentAllocations.bulkAdd(input.allocations.map(x=>({id:uid(),paymentId:payment.id,...x,...audit(input.user)})));for(const allocation of input.allocations){const invoice=(await db.supplierInvoiceRecords.get(allocation.supplierInvoiceId))!,paid=invoice.paidPiasters+allocation.amountPiasters;await db.supplierInvoiceRecords.update(invoice.id,{paidPiasters:paid,status:paid>=invoice.totalPiasters?"paid":"partially_paid",updatedAt:now()});}const account=await db.accounts.get(input.paymentAccountId),code=account?.code??(input.paymentMethod==="bank"?"1130":"1110");await createJournal({date:input.date,referenceType:"supplier_payment",referenceId:payment.id,referenceNumber:payment.reference,description:"سداد فواتير مورد",sourceModule:"purchasing",lines:[{accountCode:"2110",debitMinor:amount,creditMinor:0,description:"الموردون"},{accountCode:code,debitMinor:0,creditMinor:amount,description:"سداد نقدي أو بنكي"}]});await writeAudit({action:"supplier_payment_post",entityType:"supplier_payment",entityId:payment.id,reference:payment.reference,user:input.user,module:"purchasing",afterSummary:`amount=${amount};invoices=${input.allocations.length}`});return payment;});
}

export async function postPurchaseReturn(input:{role:UserRole;user:string;supplierId:string;goodsReceiptId?:string;supplierInvoiceId?:string;warehouseId:string;itemId:string;quantity:number;unitId:string;unitCostPiasters:number;vatRate:number;reason:PurchaseReturnRecord["reason"]}){
  await requirePermission(input.role,"purchases.return");const [item,unit]=await Promise.all([db.items.get(input.itemId),db.units.get(input.unitId)]);if(!item||!unit)throw new Error("بيانات صنف المرتجع غير مكتملة");const base=await db.units.get(item.baseUnitId);if(!base||base.family!==unit.family)throw new Error("وحدة المرتجع غير متوافقة");const quantityBase=convertUnitQuantity(input.quantity,unit.baseFactor,base.baseFactor),balance=await db.balances.get(`${input.warehouseId}:${input.itemId}`);if(input.quantity<=0||!balance||balance.quantity<quantityBase)throw new Error("الرصيد المتاح لا يكفي لمرتجع الشراء");const subtotal=Math.round(input.quantity*input.unitCostPiasters),vat=Math.round(subtotal*input.vatRate/100),total=subtotal+vat,number=await num("PRTN",db.purchaseReturnRecords),id=uid();
  return db.transaction("rw",[db.purchaseReturnRecords,db.balances,db.movements,db.accounts,db.journalEntries,db.journalLines,db.auditLogs],async()=>{await db.balances.update(balance.id,{quantity:roundQuantity(balance.quantity-quantityBase),updatedAt:now()});await db.movements.add({id:uid(),warehouseId:input.warehouseId,itemId:input.itemId,type:"purchase_return",quantity:-quantityBase,enteredQuantity:input.quantity,enteredUnitId:input.unitId,unitCostPiasters:Math.round(subtotal/quantityBase),totalCostPiasters:-subtotal,reference:number,note:input.reason,...audit(input.user)});const row:PurchaseReturnRecord={id,number,supplierId:input.supplierId,goodsReceiptId:input.goodsReceiptId,supplierInvoiceId:input.supplierInvoiceId,warehouseId:input.warehouseId,itemId:input.itemId,quantity:input.quantity,unitId:input.unitId,reason:input.reason,subtotalPiasters:subtotal,vatPiasters:vat,totalPiasters:total,status:"posted",...audit(input.user)};await db.purchaseReturnRecords.add(row);await createJournal({referenceType:"purchase_return",referenceId:id,referenceNumber:number,description:"مرتجع مشتريات",sourceModule:"purchasing",lines:[{accountCode:"2110",debitMinor:total,creditMinor:0,description:"تخفيض رصيد المورد"},{accountCode:"1210",debitMinor:0,creditMinor:subtotal,description:"رد مواد للمورد"},{accountCode:"2190",debitMinor:0,creditMinor:vat,description:"عكس ضريبة المدخلات"}].filter(x=>x.debitMinor||x.creditMinor)});await writeAudit({action:"purchase_return_post",entityType:"purchase_return",entityId:id,reference:number,user:input.user,module:"purchasing",afterSummary:`quantity=${input.quantity};total=${total}`,reason:input.reason});return row;});
}
