"use client";import {db} from "@/src/db/database";import type {SaleOrder} from "./models";
export async function salesReport(filters:{from:string;to:string;paymentMethod?:string}){const rows=(await db.saleOrders.toArray()).filter(x=>x.createdAt.slice(0,10)>=filters.from&&x.createdAt.slice(0,10)<=filters.to&&(!filters.paymentMethod||x.paymentMethod===filters.paymentMethod));return rows.flatMap(sale=>sale.items.map(item=>({date:sale.createdAt.slice(0,10),reference:sale.number,product:item.name,quantity:item.quantity,netSales:item.unitPricePiasters*item.quantity,vat:Math.round(item.unitPricePiasters*item.quantity*.14),grossSales:Math.round(item.unitPricePiasters*item.quantity*1.14),paymentMethod:sale.paymentMethod,shiftId:sale.shiftId,cogs:item.costPiasters*item.quantity,grossProfit:(item.unitPricePiasters-item.costPiasters)*item.quantity})));}
export function productProfitability(sales:SaleOrder[]){const map=new Map<string,{product:string;quantity:number;netSales:number;cogs:number}>();for(const line of sales.flatMap(x=>x.items)){const row=map.get(line.itemId)??{product:line.name,quantity:0,netSales:0,cogs:0};row.quantity+=line.quantity;row.netSales+=line.unitPricePiasters*line.quantity;row.cogs+=line.costPiasters*line.quantity;map.set(line.itemId,row)}return[...map.values()].map(x=>({...x,grossProfit:x.netSales-x.cogs,grossMargin:x.netSales?(x.netSales-x.cogs)/x.netSales*100:0}));}
export async function supplierAging(asOf=new Date().toISOString().slice(0,10)){const invoices=await db.supplierInvoiceRecords.where("status").notEqual("paid").toArray();return invoices.map(x=>{const days=Math.floor((new Date(asOf).getTime()-new Date(x.dueDate).getTime())/86400000),outstanding=x.totalPiasters-x.paidPiasters;return{supplierId:x.supplierId,reference:x.number,outstanding,bucket:days<=0?"current":days<=30?"1-30":days<=60?"31-60":days<=90?"61-90":"90+"}});}
const inRange=(date:string,filters:{from:string;to:string})=>date.slice(0,10)>=filters.from&&date.slice(0,10)<=filters.to;
export async function stockMovementReport(filters:{from:string;to:string}){const rows=(await db.movements.toArray()).filter(x=>inRange(x.createdAt,filters)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));const balances=new Map<string,number>();return rows.map(x=>{const key=`${x.warehouseId}:${x.itemId}`,running=(balances.get(key)??0)+x.quantity;balances.set(key,running);return{date:x.createdAt,reference:x.reference,itemId:x.itemId,warehouseId:x.warehouseId,movementType:x.type,quantityIn:Math.max(0,x.quantity),quantityOut:Math.max(0,-x.quantity),unitCost:x.unitCostPiasters,value:x.totalCostPiasters,runningBalance:running}});}
export async function wasteReport(filters:{from:string;to:string}){return (await db.wasteEntries.toArray()).filter(x=>inRange(x.occurredAt,filters)).map(x=>({date:x.occurredAt,reference:x.number,itemId:x.itemId,warehouseId:x.warehouseId,quantity:x.quantity,cost:x.totalCostPiasters,reason:x.reason,shiftId:x.shiftId,user:x.createdBy}));}
export async function productionReport(filters:{from:string;to:string}){return (await db.productionOrders.toArray()).filter(x=>inRange(x.createdAt,filters)).map(x=>({date:x.createdAt,productionOrder:x.number,recipeId:x.recipeId,quantityProduced:x.actualQuantity,actualCost:x.totalCostPiasters,unitCost:x.unitCostPiasters,wasteQuantity:x.wasteQuantity}));}
export async function shiftReport(filters:{from:string;to:string}){return (await db.shifts.toArray()).filter(x=>inRange(x.openedAt,filters)).map(x=>({reference:x.number,openedAt:x.openedAt,closedAt:x.closedAt,cashier:x.cashier,openingCash:x.openingCashPiasters,cashSales:x.cashSalesPiasters,cardSales:x.cardSalesPiasters,walletSales:x.walletSalesPiasters,expectedCash:x.expectedCashPiasters,actualCash:x.actualCashPiasters,difference:x.differencePiasters,orders:x.orderCount,status:x.status}));}
export async function purchaseReport(filters:{from:string;to:string}){const invoices=(await db.supplierInvoiceRecords.toArray()).filter(x=>inRange(x.invoiceDate,filters)),returns=(await db.purchaseReturnRecords.toArray()).filter(x=>inRange(x.createdAt,filters));return invoices.map(x=>({supplierId:x.supplierId,reference:x.number,date:x.invoiceDate,purchases:x.subtotalPiasters-x.discountPiasters,vat:x.vatPiasters,total:x.totalPiasters,paid:x.paidPiasters,outstanding:x.totalPiasters-x.paidPiasters,returns:returns.filter(r=>r.supplierId===x.supplierId).reduce((s,r)=>s+r.totalPiasters,0)}));}
export async function expenseReport(filters:{from:string;to:string}){return (await db.expenses.toArray()).filter(x=>inRange(x.expenseDate,filters)).map(x=>({date:x.expenseDate,category:x.category,description:x.description,paymentMethod:x.paymentMethod,amount:x.amountPiasters,vat:x.vatPiasters??0,month:x.expenseDate.slice(0,7),reference:x.reference}));}
export function exportCsv(name:string,rows:Array<Record<string,string|number|undefined>>){if(!rows.length)throw new Error("لا توجد بيانات للتصدير");const headers=Object.keys(rows[0]),escape=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`,csv="\uFEFF"+headers.map(escape).join(",")+"\n"+rows.map(r=>headers.map(h=>escape(r[h])).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=`${name}.csv`;a.click();URL.revokeObjectURL(url);}
