"use client";
import {useEffect,useMemo,useState} from "react";
import {db} from "@/src/db/database";
import type {AccountingAccount,AuditLog,CashierShift,InventoryItem,JournalLine,OperationalAlert,ProductionOrder,Recipe,RestaurantExpense,SaleOrder,ShiftCashMovement,StockBalance,StockCount,StockCountLine,StockMovement,UnitOfMeasure,UserRole,Warehouse,WasteEntry} from "@/src/domain/models";
import {openShift} from "@/src/domain/accounting-service";
import {addShiftCashMovement,approveStockCountWithApproval,closeShiftWithApproval,createStockCount,getFoodCostAnalysis,postWasteWithApproval,setCountActual} from "@/src/domain/operations-service";
import {foodCostPercent} from "@/src/domain/operations-rules";
import {formatMoney,formatQuantity} from "@/src/lib/money";
import {roleHasPermission} from "@/src/domain/authorization-service";

type Data={items:InventoryItem[];warehouses:Warehouse[];units:UnitOfMeasure[];balances:StockBalance[];saleOrders:SaleOrder[];expenses:RestaurantExpense[];productionOrders:ProductionOrder[];recipes:Recipe[];movements:StockMovement[];shifts:CashierShift[];shiftCashMovements:ShiftCashMovement[];stockCounts:StockCount[];stockCountLines:StockCountLine[];wasteEntries:WasteEntry[];alerts:OperationalAlert[];accounts:AccountingAccount[];journalLines:JournalLine[];settings?:{username?:string}};
type Tab="owner"|"shifts"|"counts"|"waste"|"food"|"alerts"|"audit";
const TODAY=new Date().toISOString().slice(0,10);
const YESTERDAY=new Date(new Date(TODAY).getTime()-86400000).toISOString().slice(0,10);
export function OperationsControlModule({data,role,user,refresh,notify}:{data:Data;role:UserRole;user:string;refresh:()=>Promise<void>;notify:(text:string,error?:boolean)=>void}){
 const [tab,setTab]=useState<Tab>("owner");const run=async(fn:()=>Promise<unknown>,message:string)=>{try{await fn();await refresh();notify(message);}catch(e){notify(e instanceof Error?e.message:"تعذر تنفيذ العملية",true);}};
 const allTabs:Array<[Tab,string]>= [["owner","لوحة المالك"],["shifts","الورديات والنقدية"],["counts","الجرد الفعلي"],["waste","الهالك"],["food","تكلفة الطعام"],["alerts","التنبيهات"],["audit","سجل المراجعة"]],allowed:Tab[]=role==="OWNER"||role==="MANAGER"?allTabs.map(x=>x[0]):role==="STOREKEEPER"?["counts","waste","alerts"]:["shifts"],tabs=allTabs.filter(x=>allowed.includes(x[0])),selected=allowed.includes(tab)?tab:allowed[0];
 return <div className="operations-control"><div className="finance-tabs">{tabs.map(([id,label])=><button key={id} className={selected===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {selected==="owner"&&<OwnerDashboard data={data}/>}
 {selected==="shifts"&&<ShiftControl data={data} role={role} user={user} run={run}/>}
 {selected==="counts"&&<StockCounts data={data} role={role} user={user} run={run}/>}
 {selected==="waste"&&<WasteControl data={data} role={role} user={user} run={run}/>}
 {selected==="food"&&<FoodCost data={data}/>}
 {selected==="alerts"&&<Alerts data={data}/>}
 {selected==="audit"&&<AuditTrail/>}</div>;
}
function Card({label,value,hint,tone}:{label:string;value:string;hint:string;tone?:string}){return <article className={`owner-kpi ${tone??""}`}><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>}
function OwnerDashboard({data}:{data:Data}){
 const todaySales=data.saleOrders.filter(x=>x.createdAt.startsWith(TODAY)),yesterday=data.saleOrders.filter(x=>x.createdAt.startsWith(YESTERDAY));const sales=todaySales.reduce((s,x)=>s+x.subtotalPiasters,0),cogs=todaySales.reduce((s,x)=>s+x.items.reduce((a,i)=>a+i.costPiasters*i.quantity,0),0),expenses=data.expenses.filter(x=>x.expenseDate===TODAY).reduce((s,x)=>s+x.amountPiasters,0),gross=sales-cogs,net=gross-expenses;const cash=todaySales.filter(x=>x.paymentMethod==="cash").reduce((s,x)=>s+x.totalPiasters,0),card=todaySales.filter(x=>x.paymentMethod==="card").reduce((s,x)=>s+x.totalPiasters,0),wallet=todaySales.filter(x=>x.paymentMethod==="wallet").reduce((s,x)=>s+x.totalPiasters,0),waste=data.wasteEntries.filter(x=>x.occurredAt.startsWith(TODAY)).reduce((s,x)=>s+x.totalCostPiasters,0);const low=data.balances.filter(b=>b.quantity<=(data.items.find(i=>i.id===b.itemId)?.minLevel??0)),out=data.balances.filter(b=>b.quantity<=0);const productSales=new Map<string,{name:string;qty:number;profit:number}>();todaySales.flatMap(x=>x.items).forEach(x=>{const v=productSales.get(x.itemId)??{name:x.name,qty:0,profit:0};v.qty+=x.quantity;v.profit+=(x.unitPricePiasters-x.costPiasters)*x.quantity;productSales.set(x.itemId,v)});const products=[...productSales.values()].sort((a,b)=>b.qty-a.qty),latest=data.shifts.filter(x=>x.status==="closed").slice(0,4);
 return <><div className="owner-grid"><Card label="مبيعات اليوم" value={formatMoney(sales)} hint={`${todaySales.length} طلب · أمس ${formatMoney(yesterday.reduce((s,x)=>s+x.subtotalPiasters,0))}`} tone="blue"/><Card label="مجمل الربح" value={formatMoney(gross)} hint={`هامش ${sales?(gross/sales*100).toFixed(1):0}%`} tone="green"/><Card label="صافي الربح" value={formatMoney(net)} hint={`مصروفات اليوم ${formatMoney(expenses)}`}/><Card label="تكلفة الطعام" value={`${foodCostPercent(cogs,sales).toFixed(1)}%`} hint={formatMoney(cogs)} tone="amber"/><Card label="نقدي" value={formatMoney(cash)} hint="تحصيل ورديات"/><Card label="بطاقات" value={formatMoney(card)} hint="تسوية بطاقات"/><Card label="محافظ" value={formatMoney(wallet)} hint="محافظ إلكترونية"/><Card label="هالك اليوم" value={formatMoney(waste)} hint={`${data.wasteEntries.filter(x=>x.occurredAt.startsWith(TODAY)).length} حركة`} tone="red"/></div>
 <div className="owner-panels"><Panel title="ما يحتاج انتباهك الآن"><div className="alert-cards"><Alert text={`${low.length} صنف منخفض`} tone="amber"/><Alert text={`${out.length} صنف نافد`} tone="red"/><Alert text={data.shifts.some(x=>x.status==="open")?"وردية مفتوحة الآن":"لا توجد وردية مفتوحة"} tone={data.shifts.some(x=>x.status==="open")?"green":"amber"}/><Alert text={`${data.alerts.filter(x=>!x.resolvedAt).length} تنبيه نشط`} tone="red"/></div></Panel><Panel title="أفضل المنتجات اليوم">{products.length?products.slice(0,5).map(x=><div className="rank-row" key={x.name}><strong>{x.name}</strong><span>{formatQuantity(x.qty)} طلب · ربح {formatMoney(x.profit)}</span></div>):<Empty text="لا توجد مبيعات اليوم"/>}</Panel></div>
 <Panel title="آخر إغلاقات الورديات">{latest.length?<div className="shift-cards">{latest.map(x=><article key={x.id}><strong>{x.number}</strong><span>مبيعات {formatMoney((x.cashSalesPiasters+x.cardSalesPiasters+x.walletSalesPiasters))}</span><span>المتوقع {formatMoney(x.expectedCashPiasters)}</span><span>الفعلي {formatMoney(x.actualCashPiasters??0)}</span><b className={(x.differencePiasters??0)<0?"negative":"positive"}>الفرق {formatMoney(x.differencePiasters??0)}</b></article>)}</div>:<Empty text="لا توجد ورديات مغلقة"/>}</Panel></>;
}
function ShiftControl({data,role,user,run}:{data:Data;role:UserRole;user:string;run:(fn:()=>Promise<unknown>,m:string)=>void}){const open=data.shifts.find(x=>x.status==="open");const [amount,setAmount]=useState(""),[actual,setActual]=useState("");return <><Panel title={open?`الوردية الحالية — ${open.number}`:"فتح وردية جديدة"}>{open?<div className="shift-live"><Card label="رصيد الافتتاح" value={formatMoney(open.openingCashPiasters)} hint={open.cashier}/><form onSubmit={e=>{e.preventDefault();run(()=>addShiftCashMovement("cash_in",Math.round(Number(amount)*100),"إضافة نقدية"),"تم تسجيل النقدية الواردة");setAmount("")}}><input type="number" step=".01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="قيمة حركة النقدية" required/><div className="row-actions"><button className="btn green">نقدية واردة</button><button type="button" className="btn danger" onClick={()=>run(()=>addShiftCashMovement("cash_out",Math.round(Number(amount)*100),"صرف نقدي"),"تم تسجيل الصرف النقدي")}>صرف نقدي</button></div></form><form onSubmit={e=>{e.preventDefault();run(()=>closeShiftWithApproval({shiftId:open.id,actualCashPiasters:Math.round(Number(actual)*100),role,user}),"تم الإغلاق أو إرسال الفرق للموافقة حسب الحد")}}><input type="number" step=".01" value={actual} onChange={e=>setActual(e.target.value)} placeholder="العد الفعلي للنقدية" required/><button className="btn primary">إغلاق الوردية</button></form></div>:<OpenShiftForm user={user} run={run}/>}</Panel><Panel title="سجل الورديات">{data.shifts.length?<div className="shift-cards">{data.shifts.map(x=><article key={x.id}><strong>{x.number} · {x.cashier}</strong><span>{new Date(x.openedAt).toLocaleString("ar-EG")}</span><span>المبيعات {formatMoney(x.cashSalesPiasters+x.cardSalesPiasters+x.walletSalesPiasters)}</span><span>المتوقع {formatMoney(x.expectedCashPiasters)}</span><b className={(x.differencePiasters??0)<0?"negative":"positive"}>{x.status==="open"?"مفتوحة":`${x.differenceStatus==="shortage"?"عجز":x.differenceStatus==="surplus"?"زيادة":"متوازنة"} · ${formatMoney(x.differencePiasters??0)}`}</b></article>)}</div>:<Empty text="ابدأ بأول وردية"/>}</Panel></>}
function OpenShiftForm({user,run}:{user:string;run:(fn:()=>Promise<unknown>,m:string)=>void}){const [opening,setOpening]=useState("0"),[notes,setNotes]=useState("");return <form className="inline-form" onSubmit={e=>{e.preventDefault();run(()=>openShift(user,Math.round(Number(opening)*100),notes),"تم فتح الوردية")}}><label>الكاشير<input value={user} disabled/></label><label>رصيد الافتتاح<input type="number" step=".01" value={opening} onChange={e=>setOpening(e.target.value)} required/></label><label>ملاحظات<input value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="btn primary">فتح وردية</button></form>}
function StockCounts({data,role,user,run}:{data:Data;role:UserRole;user:string;run:(fn:()=>Promise<unknown>,m:string)=>void}){const active=data.stockCounts.find(x=>x.status!=="approved");return <><Panel title="جرد المخزون الفعلي">{active?<CountEditor count={active} data={data} role={role} user={user} run={run}/>:<form className="inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>createStockCount(String(f.get("warehouse")),String(f.get("notes"))),"تم إنشاء الجرد دون تعديل الأرصدة")}}><select name="warehouse" required><option value="">اختر المخزن</option>{data.warehouses.map(x=><option key={x.id} value={x.id}>{x.nameAr}</option>)}</select><input name="notes" placeholder="ملاحظات الجرد"/><button className="btn primary">إنشاء جرد</button></form>}</Panel><Panel title="سجل الجرد"><div className="shift-cards">{data.stockCounts.map(x=>{const lines=data.stockCountLines.filter(l=>l.stockCountId===x.id),short=lines.filter(l=>l.differenceQuantity<0).length,sur=lines.filter(l=>l.differenceQuantity>0).length;return <article key={x.id}><strong>{x.number}</strong><span>{data.warehouses.find(w=>w.id===x.warehouseId)?.nameAr}</span><span>عجز {short} · زيادة {sur}</span><b>{x.status==="approved"?"معتمد":x.status==="reviewed"?"بانتظار الموافقة":"قيد الجرد"}</b></article>})}</div></Panel></>}
function CountEditor({count,data,role,user,run}:{count:StockCount;data:Data;role:UserRole;user:string;run:(fn:()=>Promise<unknown>,m:string)=>void}){const lines=data.stockCountLines.filter(x=>x.stockCountId===count.id);return <div><div className="table-wrap"><table><thead><tr><th>الصنف</th><th>رصيد النظام</th><th>الفعلي</th><th>الفرق</th><th>قيمة الفرق</th></tr></thead><tbody>{lines.map(line=>{const item=data.items.find(x=>x.id===line.itemId),unit=data.units.find(x=>x.id===line.unitId);return <tr key={line.id}><td>{item?.nameAr}</td><td>{formatQuantity(line.systemQuantity)} {unit?.symbol}</td><td><input className="count-input" type="number" step=".001" defaultValue={line.actualQuantity} onBlur={e=>run(()=>setCountActual(line.id,Number(e.target.value),line.unitId),"تم تحديث كمية الجرد")}/></td><td className={line.differenceQuantity<0?"negative":"positive"}>{formatQuantity(line.differenceQuantity)}</td><td>{formatMoney(line.differenceValuePiasters)}</td></tr>})}</tbody></table></div>{count.status!=="reviewed"&&roleHasPermission(role,"stock_count.approve")?<button className="btn primary" onClick={()=>run(()=>approveStockCountWithApproval({countId:count.id,role,user}),"تم الاعتماد أو إرسال فرق الجرد للموافقة حسب الحد")}>اعتماد الجرد</button>:<p className="cell-sub">يحفظ أمين المخزن العد الفعلي، ويعتمد المدير فرق الجرد.</p>}</div>}
function WasteControl({data,role,user,run}:{data:Data;role:UserRole;user:string;run:(fn:()=>Promise<unknown>,m:string)=>void}){const month=TODAY.slice(0,7),rows=data.wasteEntries.filter(x=>x.occurredAt.startsWith(month));const reasons=new Map<string,number>();rows.forEach(x=>reasons.set(x.reason,(reasons.get(x.reason)??0)+x.totalCostPiasters));return <><div className="owner-grid compact"><Card label="هالك اليوم" value={formatMoney(rows.filter(x=>x.occurredAt.startsWith(TODAY)).reduce((s,x)=>s+x.totalCostPiasters,0))} hint="تكلفة فعلية" tone="red"/><Card label="هالك الشهر" value={formatMoney(rows.reduce((s,x)=>s+x.totalCostPiasters,0))} hint={`${rows.length} حركة`} tone="amber"/><Card label="أعلى سبب" value={[...reasons.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]??"—"} hint="حسب التكلفة"/></div><Panel title="تسجيل هالك معلوم"><WasteForm data={data} role={role} user={user} run={run}/></Panel><Panel title="سجل الهالك"><div className="shift-cards">{data.wasteEntries.map(x=><article key={x.id}><strong>{x.number} · {data.items.find(i=>i.id===x.itemId)?.nameAr}</strong><span>{data.warehouses.find(w=>w.id===x.warehouseId)?.nameAr} · {x.reason}</span><span>{formatQuantity(x.enteredQuantity)} {data.units.find(u=>u.id===x.unitId)?.symbol}</span><b className="negative">{formatMoney(x.totalCostPiasters)}</b></article>)}</div></Panel></>}
function WasteForm({data,role,user,run}:{data:Data;role:UserRole;user:string;run:(fn:()=>Promise<unknown>,m:string)=>void}){const [warehouse,setWarehouse]=useState(""),[item,setItem]=useState("");const available=data.balances.filter(x=>x.warehouseId===warehouse&&x.quantity>0);const selected=data.items.find(x=>x.id===item);const units=data.units.filter(u=>u.family===data.units.find(x=>x.id===selected?.baseUnitId)?.family);return <form className="inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>postWasteWithApproval({warehouseId:warehouse,itemId:item,enteredQuantity:Number(f.get("quantity")),unitId:String(f.get("unit")),reason:String(f.get("reason")) as Parameters<typeof postWasteWithApproval>[0]["reason"],notes:String(f.get("notes")),role,user}),"تم الخصم أو إرسال الهالك للموافقة حسب الحد")}}><select value={warehouse} onChange={e=>{setWarehouse(e.target.value);setItem("")}} required><option value="">المخزن/المرحلة</option>{data.warehouses.map(x=><option key={x.id} value={x.id}>{x.nameAr}</option>)}</select><select value={item} onChange={e=>setItem(e.target.value)} required><option value="">الصنف</option>{available.map(b=><option key={b.itemId} value={b.itemId}>{data.items.find(i=>i.id===b.itemId)?.nameAr} — {formatQuantity(b.quantity)}</option>)}</select><input name="quantity" type="number" step=".001" min=".001" placeholder="الكمية" required/><select name="unit" required><option value="">الوحدة</option>{units.map(x=><option key={x.id} value={x.id}>{x.nameAr}</option>)}</select><select name="reason" required><option value="spoiled">تالف</option><option value="expired">منتهي الصلاحية</option><option value="burned">محروق</option><option value="dropped">سقط</option><option value="overproduction">إنتاج زائد</option><option value="preparation">هالك تجهيز</option><option value="damaged">متضرر</option><option value="other">أخرى</option></select><input name="notes" placeholder="ملاحظات"/><button className="btn danger">اعتماد الهالك</button></form>}
type FoodRow=Awaited<ReturnType<typeof getFoodCostAnalysis>>[number];
function FoodCost({data}:{data:Data}){const [rows,setRows]=useState<FoodRow[]>([]);useEffect(()=>{getFoodCostAnalysis().then(setRows)},[data.productionOrders,data.items]);const sales=data.saleOrders.reduce((s,x)=>s+x.subtotalPiasters,0),cogs=data.saleOrders.reduce((s,x)=>s+x.items.reduce((a,i)=>a+i.costPiasters*i.quantity,0),0);return <><div className="owner-grid compact"><Card label="Food Cost الفعلي" value={`${foodCostPercent(cogs,sales).toFixed(1)}%`} hint="من المبيعات الفعلية"/><Card label="تكلفة المبيعات" value={formatMoney(cogs)} hint="بدون نسب معيارية"/><Card label="صافي مبيعات الطعام" value={formatMoney(sales)} hint="بيانات الكاشير"/></div><Panel title="المعياري مقابل الفعلي"><div className="table-wrap"><table><thead><tr><th>المنتج</th><th>تكلفة الوصفة</th><th>المعياري للإنتاج</th><th>التكلفة الفعلية</th><th>الفرق</th><th>سعر البيع</th></tr></thead><tbody>{rows.map(x=><tr key={x.recipeId}><td><strong>{x.name}</strong><small className="cell-sub">{x.productionOrders} أمر تصنيع</small></td><td>{formatMoney(x.standardCostPiasters)}</td><td>{formatMoney(x.standardForActualPiasters)}</td><td>{formatMoney(x.actualCostPiasters)}</td><td className={x.variancePiasters>0?"negative":"positive"}>{formatMoney(x.variancePiasters)}</td><td>{formatMoney(x.sellingPricePiasters)}</td></tr>)}</tbody></table></div></Panel><Panel title="تأثير أسعار المكونات">{data.items.filter(i=>i.stage!=="finished").map(item=>{const affected=data.recipes.filter(r=>r.ingredients.some(i=>i.itemId===item.id));return affected.length?<div className="rank-row" key={item.id}><strong>{item.nameAr} · {formatMoney(item.averageCostPiasters)}</strong><span>{affected.map(r=>r.nameAr).join("، ")}</span></div>:null})}</Panel></>}
function Alerts({data}:{data:Data}){const derived=useMemo(()=>data.balances.flatMap(b=>{const item=data.items.find(i=>i.id===b.itemId);if(!item)return[];if(b.quantity<=0)return[`نفاد ${item.nameAr}`];if(b.quantity<=item.minLevel)return[`رصيد منخفض: ${item.nameAr}`];return[]}),[data.balances,data.items]);return <Panel title="التنبيهات التشغيلية داخل النظام"><div className="alert-list">{derived.map(x=><Alert key={x} text={x} tone="red"/>)}{data.alerts.filter(x=>!x.resolvedAt).map(x=><Alert key={x.id} text={`${x.title} — ${x.message}`} tone={x.severity==="critical"?"red":"amber"}/>)}{!derived.length&&!data.alerts.length&&<Empty text="لا توجد تنبيهات حالية"/>}</div></Panel>}
function AuditTrail(){const [rows,setRows]=useState<AuditLog[]>([]),[date,setDate]=useState(""),[user,setUser]=useState(""),[module,setModule]=useState(""),[action,setAction]=useState(""),[reference,setReference]=useState("");useEffect(()=>{db.auditLogs.orderBy("timestamp").reverse().toArray().then(setRows)},[]);const shown=rows.filter(x=>(!date||x.timestamp.startsWith(date))&&(!user||x.localUser.toLowerCase().includes(user.toLowerCase()))&&(!module||(x.module??x.entityType).toLowerCase().includes(module.toLowerCase()))&&(!action||x.action.toLowerCase().includes(action.toLowerCase()))&&(!reference||x.reference.toLowerCase().includes(reference.toLowerCase())));return <Panel title="سجل مراجعة العمليات الحرجة"><div className="inline-form"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><input placeholder="المستخدم" value={user} onChange={e=>setUser(e.target.value)}/><input placeholder="الوحدة / القسم" value={module} onChange={e=>setModule(e.target.value)}/><input placeholder="العملية" value={action} onChange={e=>setAction(e.target.value)}/><input placeholder="المرجع" value={reference} onChange={e=>setReference(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>الوقت</th><th>الوحدة</th><th>العملية</th><th>الكيان</th><th>المرجع</th><th>المستخدم</th><th>قبل</th><th>بعد / السبب</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td>{new Date(x.timestamp).toLocaleString("ar-EG")}</td><td>{x.module??"—"}</td><td>{x.action}</td><td>{x.entityType}</td><td>{x.reference}</td><td>{x.userName??x.localUser}</td><td>{x.beforeSummary??"—"}</td><td>{x.afterSummary??x.reason??"—"}</td></tr>)}</tbody></table></div></Panel>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><h3>{title}</h3></div><div className="panel-body">{children}</div></section>}function Alert({text,tone}:{text:string;tone:string}){return <div className={`operation-alert ${tone}`}>{text}</div>}function Empty({text}:{text:string}){return <p className="empty-state">{text}</p>}
